# Generated by Django 5.2.3 on 2025-07-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('ID_Hist_med', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(help_text='Fecha en que se realizó el diagnóstico.')),
                ('diagnostico', models.TextField(help_text='Descripción del diagnóstico médico.')),
                ('tratamiento', models.TextField(help_text='Tratamiento prescrito para el diagnóstico.')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales del médico.', null=True)),
                ('medicamentos', models.TextField(blank=True, help_text='Medicamentos recetados al paciente.', null=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SeguroMedico',
            fields=[
                ('ID_Seg', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre de la compañía de seguros.', max_length=100)),
                ('cobertura', models.TextField(help_text='Descripción de la cobertura del seguro.')),
                ('telefono', models.CharField(help_text='Teléfono de contacto de la aseguradora.', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico de la aseguradora.', max_length=100)),
            ],
        ),
    ]
