# Generated by Django 5.2.3 on 2025-07-03 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Historial_Med', '0001_initial'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmedico',
            name='paciente',
            field=models.ForeignKey(help_text='Referencia al paciente (Paciente.ID_Paciente).', on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='Usuarios.paciente'),
        ),
        migrations.AddField(
            model_name='seguromedico',
            name='paciente',
            field=models.OneToOneField(help_text='Paciente asegurado.', on_delete=django.db.models.deletion.CASCADE, related_name='seguro', to='Usuarios.paciente'),
        ),
    ]
