# Generated by Django 5.2.3 on 2025-07-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha programada para la cita.')),
                ('hora', models.TimeField(help_text='Hora programada para la cita.')),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada')], default='PROGRAMADA', help_text='El estado actual de la cita.', max_length=20)),
            ],
            options={
                'ordering': ['fecha', 'hora'],
            },
        ),
    ]
