# Generated by Django 5.2.3 on 2025-07-03 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clinica', '0001_initial'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariomedico',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='Usuarios.medico'),
        ),
        migrations.AlterUniqueTogether(
            name='horariomedico',
            unique_together={('medico', 'dia', 'hora_inicio', 'hora_fin')},
        ),
    ]
